// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ShrimplePomodoroTimer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>Shrimple Pomodoro Timer</title><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"description\" content=\"\"><link rel=\"icon\" href=\"https://fav.farm/🦐\"><link rel=\"stylesheet\" href=\"output.css\"></head><body data-type class=\"\n\t\t\tmin-h-svh p-12\n\t\t\tbg-blue-500\n\t\t\ttext-blue-100\n\t\t\tdata-[type=work]:bg-orange-500\n\t\t\tdata-[type=work]:text-orange-100\n\t\t\tdata-[type=break]:bg-teal-500\n\t\t\tdata-[type=break]:text-teal-100\n\t\t\ttransition-all\n\t\t\tduration-1000\n\t\t\tflex flex-col\n\t\t\titems-center\n\t\t\t\"><div id=\"time-left\" class=\"text-5xl sm:text-9xl font-mono\">--:--</div><div id=\"end-time\">-</div><div class=\"flex flex-wrap gap-2 justify-center mt-4\"><button data-time=\"1500\" data-type=\"work\" class=\"hover:bg-white/10 p-4\">Start Pomodoro</button> <button data-time=\"300\" data-type=\"break\" class=\"hover:bg-white/10 p-4\">Start Break</button></div><div class=\"flex flex-col gap-2 justify-center mt-4\"><audio id=\"workBell\" controls><source src=\"/work.mp3\"></audio> <audio id=\"breakBell\" controls><source src=\"/break.mp3\"></audio></div><script src=\"shrimple-pomodoro-timer.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
