services:
  webserver-dev:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.webserver-dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/app
  tailwindcss:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.tailwindcss
    volumes:
      - ../:/app
    tty: true
    command: >
      -i ./input.css
      -o ./public/output.css
      --watch --poll
  webserver-prod:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.webserver-prod
    ports:
      - "3000:3000"
